// Generated by CoffeeScript 1.6.3
(function() {
  var assert, gqexpress;

  gqexpress = require("../../gqexpress");

  assert = require("assert");

  it("should be able to start the server", function(done) {
    return gqexpress.startServer({
      set: function(app, o) {
        app.set("doing", "test");
        return app;
      },
      use: function(app, o) {
        app.get("/", function(req, res) {
          return res.render("index", {
            title: "gqexpress"
          });
        });
        return app;
      }
    }, function(e, o) {
      console.log(" All done!");
      assert(o.message);
      return setTimeout(function() {
        return done(e);
      }, 500);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=test.map
*/
