// Generated by CoffeeScript 1.6.3
(function() {
  var gqexpress;

  gqexpress = require("../gqexpress");

  gqexpress.startServer({
    set: function(app, o) {
      app.set("doing", "test");
      return app;
    },
    use: function(app, o) {
      app.get("/", function(req, res) {
        return res.render("index", {
          title: "gqexpress"
        });
      });
      return app;
    },
    config: {
      server: {
        forceSecure: false
      }
    }
  }, function(e, o) {
    return console.log(" All done!");
  });

}).call(this);

/*
//@ sourceMappingURL=run.map
*/
